[build]
  publish = "public"
  command = "hugo --gc --minify --baseURL $URL"

[context.production.environment]
  HUGO_VERSION = "0.121.2"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --baseURL $DEPLOY_PRIME_URL"
