[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  # KITA PAKSA PAKAI VERSI 0.117.0 (VERSI EMAS UNTUK TEMA STACK)
  HUGO_VERSION = "0.117.0"
  HUGO_ENV = "production"
  GO_VERSION = "1.21"
